// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/category/submit.ts";
import * as $$$$$$$$$1 from "./actions/contact/submit.ts";
import * as $$$$$$$$$2 from "./actions/domains/submit.ts";
import * as $$$$$$$$$3 from "./actions/product/submit.ts";
import * as $$$$$$$$$4 from "./actions/product/update/basicData.ts";
import * as $$$0 from "./loaders/menu.ts";
import * as $$$1 from "./loaders/product/avaliableBrands.ts";
import * as $$$2 from "./loaders/product/avaliableCategories.ts";
import * as $$$3 from "./loaders/product/avaliableSites.ts";
import * as $$$4 from "./loaders/product/avaliableSkus.ts";
import * as $$$5 from "./loaders/product/details/productDetails.ts";
import * as $$$$$$0 from "./sections/Component.tsx";
import * as $$$$$$16 from "./sections/container/Container.tsx";
import * as $$$$$$1 from "./sections/Content/Banner.tsx";
import * as $$$$$$2 from "./sections/Content/Breadcrumb.tsx";
import * as $$$$$$3 from "./sections/Content/Cards.tsx";
import * as $$$$$$4 from "./sections/Content/TextCards.tsx";
import * as $$$$$$5 from "./sections/Content/Toast.tsx";
import * as $$$$$$6 from "./sections/Footer/Footer.tsx";
import * as $$$$$$7 from "./sections/Header/Header.tsx";
import * as $$$$$$8 from "./sections/Institutional/Policy.tsx";
import * as $$$$$$9 from "./sections/Institutional/Support.tsx";
import * as $$$$$$10 from "./sections/Institutional/WhereToBuy.tsx";
import * as $$$$$$17 from "./sections/mySection.tsx";
import * as $$$$$$11 from "./sections/Product/ProductDetails/AdditionalPropertyCards.tsx";
import * as $$$$$$12 from "./sections/Product/ProductDetails/ProductDetails.tsx";
import * as $$$$$$13 from "./sections/Product/ProductDetails/ProductPage.tsx";
import * as $$$$$$14 from "./sections/Product/ProductMain.tsx";
import * as $$$$$$15 from "./sections/Social/ContactForm.tsx";

const manifest = {
  "loaders": {
    "elux-components-app/loaders/menu.ts": $$$0,
    "elux-components-app/loaders/product/avaliableBrands.ts": $$$1,
    "elux-components-app/loaders/product/avaliableCategories.ts": $$$2,
    "elux-components-app/loaders/product/avaliableSites.ts": $$$3,
    "elux-components-app/loaders/product/avaliableSkus.ts": $$$4,
    "elux-components-app/loaders/product/details/productDetails.ts": $$$5,
  },
  "sections": {
    "elux-components-app/sections/Component.tsx": $$$$$$0,
    "elux-components-app/sections/container/Container.tsx": $$$$$$16,
    "elux-components-app/sections/Content/Banner.tsx": $$$$$$1,
    "elux-components-app/sections/Content/Breadcrumb.tsx": $$$$$$2,
    "elux-components-app/sections/Content/Cards.tsx": $$$$$$3,
    "elux-components-app/sections/Content/TextCards.tsx": $$$$$$4,
    "elux-components-app/sections/Content/Toast.tsx": $$$$$$5,
    "elux-components-app/sections/Footer/Footer.tsx": $$$$$$6,
    "elux-components-app/sections/Header/Header.tsx": $$$$$$7,
    "elux-components-app/sections/Institutional/Policy.tsx": $$$$$$8,
    "elux-components-app/sections/Institutional/Support.tsx": $$$$$$9,
    "elux-components-app/sections/Institutional/WhereToBuy.tsx": $$$$$$10,
    "elux-components-app/sections/mySection.tsx": $$$$$$17,
    "elux-components-app/sections/Product/ProductDetails/AdditionalPropertyCards.tsx":
      $$$$$$11,
    "elux-components-app/sections/Product/ProductDetails/ProductDetails.tsx":
      $$$$$$12,
    "elux-components-app/sections/Product/ProductDetails/ProductPage.tsx":
      $$$$$$13,
    "elux-components-app/sections/Product/ProductMain.tsx": $$$$$$14,
    "elux-components-app/sections/Social/ContactForm.tsx": $$$$$$15,
  },
  "actions": {
    "elux-components-app/actions/category/submit.ts": $$$$$$$$$0,
    "elux-components-app/actions/contact/submit.ts": $$$$$$$$$1,
    "elux-components-app/actions/domains/submit.ts": $$$$$$$$$2,
    "elux-components-app/actions/product/submit.ts": $$$$$$$$$3,
    "elux-components-app/actions/product/update/basicData.ts": $$$$$$$$$4,
  },
  "name": "elux-components-app",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
